### ISSUE TITLE
Reverse mode...

### ISSUE THREAD

**Issue by netRunner0** [rgavril/homebridge-mqtt-fan-tasmota#3]
I am using the latest Tasmot firmware.

The fan in the homekit works in reverse mode)

Maximum speed = this is the minimum work and vice versa. How to fix it?)

**Comment by mkormendy** [comment]
> The fan in the homekit works in reverse mode)
> Maximum speed = this is the minimum work and vice versa. How to fix it?)

This doesn't make sense. Please rephrase your question.

**Comment by netRunner0** [comment]
In the homekit, the rotation percentage is 33, and in fact on the fan 100%
In the homekit percentage of 100, and actually rotates by 33%
Only 67% work correctly.

**Comment by mkormendy** [comment]
Did you replace the capacitor? This is a known hardware issue with the Chinese fans vs other fans.

**Comment by netRunner0** [comment]
![IMG_0318](https://user-images.githubusercontent.com/44049295/61583382-b857b580-ab50-11e9-92aa-5b850b88b40c.jpeg)
It works with all fans. Look at the code of the Tasmota, they said that this behavior is normal when 1 is the maximum speed, and 3 is the minimum!

**Comment by mkormendy** [comment]
I don’t have this issue. Maybe there is a switch in your fan that changes the direction? Or maybe the fans you have are all wired differently.

**Comment by rgavril** [comment]
Looks like a Tasmota firmware or hardware issues.

With the Tasmota firmware, Speed 1 should be minimum speed and Speed 3 should be maximum and this is what this plugin operates.

I would suggest reporting your issue to Tasmota. It has a larger user base and if this issue is not isolated to your setup maybe they implement a workaround for it in the firmware.
